// GENESIS: Der Kreislauf des Lebens

#pragma once

#include "NativeGameplayTags.h"

/** Symptome, Zustände und Körperregionen, die die Body Simulation direkt verwendet. */
namespace GenesisBodyTags
{
	// --- Symptome: das, was der Spieler erlebt (Postprocess, Animation, Audio lesen diese) ---
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Fatigue);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Breathlessness);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_HeartPounding);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Pain);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Fever);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_BlurredVision);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_MuffledHearing);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Hunger);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Thirst);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Tremor);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Dizziness);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Stiffness);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Symptom_Nausea);

	// --- Zustände ---
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Condition_Injury);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Condition_Infection);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Condition_RespiratoryDistress);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Condition_Cardiac);

	// --- Körperregionen ---
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region_Head);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region_Torso);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region_Arm);
	GENESISBODY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Region_Leg);
}
