// GENESIS: Der Kreislauf des Lebens

#pragma once

#include "NativeGameplayTags.h"

/**
 * Systemweite native Gameplay Tags.
 *
 * Regel: Tags, die C++-Logik direkt verwendet, werden nativ deklariert (Tippfehler = Compilerfehler).
 * Inhaltliche Tags (Handlungen, Kulturen, Themen, Orte) liegen in Config/Tags/*.ini und werden
 * von Designern gepflegt. Modulspezifische native Tags liegen im jeweiligen Modul.
 */
namespace GenesisTags
{
	// --- Lebensphasen des Kreislaufs ---
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Conception);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Embryo);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Birth);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Childhood);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Youth);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Adulthood);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Elder);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Death);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Ghost);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Afterlife);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Rebirth);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_CosmicConsciousness);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LifePhase_Creation);

	// --- Die 14 verbundenen Systeme der Life Simulation Engine ---
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_Karma);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_ConsequenceNetwork);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_Indoctrination);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_EgoismAltruism);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_Trust);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_ReputationRumors);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_GroupPressure);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_Zeitgeist);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_CulturalIdentity);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_Belief);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_Propaganda);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_DoubleStandard);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_Misunderstanding);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SimSystem_Epigenetics);

	// --- Universelle Lebensthemen (Echos, Erinnerungen, Konsequenzen, Director) ---
	// Inhalte können beliebige Unter-Tags anlegen, z. B. Genesis.Theme.Loss.Parent
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Trust);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Betrayal);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Abandonment);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Care);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Love);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Loss);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Fear);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Courage);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Honesty);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Deception);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Belonging);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Freedom);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Power);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Theme_Forgiveness);

	// --- Sinne (Wahrnehmung, Erinnerungs-Trigger) ---
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sense_Sight);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sense_Hearing);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sense_Smell);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sense_Taste);
	GENESISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sense_Touch);
}
